// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {nativewindow} from '../models';

export function CancelClose(arg1:string):Promise<nativewindow.OperationResult>;

export function Close(arg1:string):Promise<nativewindow.OperationResult>;

export function CloseAll():Promise<nativewindow.OperationResult>;

export function Focus(arg1:string):Promise<nativewindow.OperationResult>;

export function List():Promise<Array<nativewindow.WindowInfo>>;

export function Open(arg1:nativewindow.OpenRequest):Promise<nativewindow.OperationResult>;

export function OpenResult(arg1:nativewindow.OpenRequest):Promise<nativewindow.OperationResult>;

export function SyncHostState(arg1:nativewindow.HostStateRequest):Promise<nativewindow.OperationResult>;
