// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClose(arg1) {
  return window['go']['nativewindow']['Manager']['CancelClose'](arg1);
}

export function Close(arg1) {
  return window['go']['nativewindow']['Manager']['Close'](arg1);
}

export function CloseAll() {
  return window['go']['nativewindow']['Manager']['CloseAll']();
}

export function Focus(arg1) {
  return window['go']['nativewindow']['Manager']['Focus'](arg1);
}

export function Hide(arg1) {
  return window['go']['nativewindow']['Manager']['Hide'](arg1);
}

export function List() {
  return window['go']['nativewindow']['Manager']['List']();
}

export function Open(arg1) {
  return window['go']['nativewindow']['Manager']['Open'](arg1);
}

export function OpenResult(arg1) {
  return window['go']['nativewindow']['Manager']['OpenResult'](arg1);
}

export function SyncHostState(arg1) {
  return window['go']['nativewindow']['Manager']['SyncHostState'](arg1);
}
