// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {sqlaudit} from '../models';
import {sync} from '../models';
import {app} from '../models';
import {jvm} from '../models';
import {redis} from '../models';
import {resultdiff} from '../models';

export function ApplyChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function ApplyDataRootDirectory(arg1:string,arg2:boolean):Promise<connection.QueryResult>;

export function ApplyLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function BuildSQLAuditExport(arg1:sqlaudit.Filter,arg2:string):Promise<connection.QueryResult>;

export function CancelApplicationQuit():Promise<connection.QueryResult>;

export function CancelQuery(arg1:string):Promise<connection.QueryResult>;

export function CancelSQLFileExecution(arg1:string):Promise<connection.QueryResult>;

export function CheckDriverNetworkStatus():Promise<connection.QueryResult>;

export function CheckForUpdates():Promise<connection.QueryResult>;

export function CheckForUpdatesSilently():Promise<connection.QueryResult>;

export function ClearSQLAuditEvents(arg1:number):Promise<connection.QueryResult>;

export function ClearSlowQueries(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ClearTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function ConfigureDriverRuntimeDirectory(arg1:string):Promise<connection.QueryResult>;

export function ConfigureGlobalProxy(arg1:boolean,arg2:connection.ProxyConfig):Promise<connection.QueryResult>;

export function CopyTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function CreateDatabase(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function CreateSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBCommitTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBCommitTransactionWithTrigger(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function DBConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetAllColumns(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetColumns(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetForeignKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetIndexes(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetObjects(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetTriggers(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetViews(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryAI(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryAudited(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryIsolated(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryMulti(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryMultiInTransaction(arg1:string,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryMultiTransactional(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryWithCancel(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBReleaseConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBRollbackTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBRollbackTransactionWithTrigger(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function DBShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DataSync(arg1:sync.SyncConfig):Promise<sync.SyncResult>;

export function DataSyncAnalyze(arg1:sync.SyncConfig):Promise<connection.QueryResult>;

export function DataSyncPreview(arg1:sync.SyncConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteQuery(arg1:string):Promise<void>;

export function DeleteSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function DeleteSQLFile(arg1:string):Promise<connection.QueryResult>;

export function DeleteSavedQueryGroup(arg1:string):Promise<void>;

export function DiagnoseQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DismissSecurityUpdateReminder():Promise<app.SecurityUpdateStatus>;

export function DownloadDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DownloadUpdate():Promise<connection.QueryResult>;

export function DropDatabase(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DropFunction(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DropSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DropTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DropView(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DuplicateConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function ExecuteSQLFile(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportConnectionsPackage(arg1:app.ConnectionExportOptions):Promise<connection.QueryResult>;

export function ExportConnectionsPayload(arg1:app.ConnectionExportOptions):Promise<connection.QueryResult>;

export function ExportData(arg1:Array<Record<string, any>>,arg2:Array<string>,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportDataWithOptions(arg1:Array<Record<string, any>>,arg2:Array<string>,arg3:string,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportDatabaseSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean):Promise<connection.QueryResult>;

export function ExportDatabaseSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportDatabasesSQLWithOptions(arg1:connection.ConnectionConfig,arg2:Array<string>,arg3:boolean,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<connection.QueryResult>;

export function ExportQueryWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportSQLAuditFile(arg1:sqlaudit.Filter,arg2:string):Promise<connection.QueryResult>;

export function ExportSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ExportSchemaSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:boolean):Promise<connection.QueryResult>;

export function ExportSchemaSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:boolean,arg5:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportTableWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportTablesDataSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function ExportTablesSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>,arg4:boolean):Promise<connection.QueryResult>;

export function ExportTablesSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>,arg4:boolean,arg5:boolean,arg6:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ForceQuitApplication():Promise<connection.QueryResult>;

export function GenerateQueryID():Promise<string>;

export function GetAppInfo():Promise<connection.QueryResult>;

export function GetDataRootDirectoryInfo():Promise<connection.QueryResult>;

export function GetDriverStatusList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionPackageSize(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetEditableSavedConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function GetGlobalProxyConfig():Promise<connection.QueryResult>;

export function GetSQLAuditEvents(arg1:sqlaudit.Filter):Promise<connection.QueryResult>;

export function GetSQLAuditHealth():Promise<connection.QueryResult>;

export function GetSQLAuditSettings():Promise<connection.QueryResult>;

export function GetSavedConnections():Promise<Array<connection.SavedConnectionView>>;

export function GetSavedQueries():Promise<Array<connection.SavedQuery>>;

export function GetSavedQueryGroups():Promise<Array<connection.SavedQueryGroup>>;

export function GetSecurityUpdateStatus():Promise<app.SecurityUpdateStatus>;

export function GetSlowQueries(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function GetUnboundSavedQueries():Promise<Array<connection.SavedQuery>>;

export function GetUpdateChannel():Promise<connection.QueryResult>;

export function ImportConfigFile():Promise<connection.QueryResult>;

export function ImportConnectionsPayload(arg1:string,arg2:string):Promise<app.ConnectionPackageImportResult>;

export function ImportData(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function ImportDataWithProgress(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ImportDataWithProgressOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:app.ImportFileOptions):Promise<connection.QueryResult>;

export function ImportLegacyConnections(arg1:Array<connection.SavedConnectionInput>):Promise<Array<connection.SavedConnectionView>>;

export function ImportLegacyGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function ImportSavedQueries(arg1:connection.SavedQueryImportPayload):Promise<Array<connection.SavedQuery>>;

export function InstallLocalDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function InstallUpdateAndRestart(arg1:boolean):Promise<connection.QueryResult>;

export function JVMApplyChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMCancelDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function JVMExecuteDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:jvm.DiagnosticCommandRequest):Promise<connection.QueryResult>;

export function JVMGetMonitoringHistory(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMListAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListDiagnosticAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListResources(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMPreviewChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMProbeCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMProbeDiagnosticCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStartDiagnosticSession(arg1:connection.ConnectionConfig,arg2:jvm.DiagnosticSessionRequest):Promise<connection.QueryResult>;

export function JVMStartMonitoring(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStopMonitoring(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ListInstalledFontFamilies():Promise<connection.QueryResult>;

export function ListSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function LogWindowDiagnostic(arg1:string,arg2:string):Promise<void>;

export function MongoDiscoverMembers(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MoveSavedQueryGroup(arg1:string,arg2:string):Promise<void>;

export function MoveSavedQueryToGroup(arg1:string,arg2:string):Promise<void>;

export function MySQLConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function MySQLQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function MySQLShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function OpenDataRootDirectory():Promise<connection.QueryResult>;

export function OpenDownloadedUpdateDirectory():Promise<connection.QueryResult>;

export function OpenDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function OpenLogDirectory():Promise<connection.QueryResult>;

export function OpenSQLFile():Promise<connection.QueryResult>;

export function PreviewChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function PreviewImportFile(arg1:string):Promise<connection.QueryResult>;

export function ReadAppLogTail(arg1:number,arg2:string):Promise<connection.QueryResult>;

export function ReadSQLFile(arg1:string):Promise<connection.QueryResult>;

export function RebindSavedQuery(arg1:string,arg2:string):Promise<connection.SavedQuery>;

export function RedisConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisDeleteHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:any):Promise<connection.QueryResult>;

export function RedisDeleteKeys(arg1:connection.ConnectionConfig,arg2:Array<string>):Promise<connection.QueryResult>;

export function RedisExecuteCommand(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisExportKeys(arg1:connection.ConnectionConfig,arg2:app.RedisExportKeysOptions):Promise<connection.QueryResult>;

export function RedisFlushDB(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetServerInfo(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisImportKeys(arg1:connection.ConnectionConfig,arg2:app.RedisImportKeysOptions):Promise<connection.QueryResult>;

export function RedisKeyExists(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisListPush(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisListRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RedisListSet(arg1:connection.ConnectionConfig,arg2:string,arg3:number,arg4:string):Promise<connection.QueryResult>;

export function RedisPreviewImportKeys(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisRenameKey(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RedisScanKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:any,arg4:number):Promise<connection.QueryResult>;

export function RedisSelectDB(arg1:connection.ConnectionConfig,arg2:number):Promise<connection.QueryResult>;

export function RedisSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RedisSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetString(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function RedisSetTTL(arg1:connection.ConnectionConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function RedisStreamAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Record<string, string>,arg4:string):Promise<connection.QueryResult>;

export function RedisStreamDelete(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisTestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisZSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<redis.ZSetMember>):Promise<connection.QueryResult>;

export function RedisZSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RemoveDriverPackage(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameDatabase(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RenameSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RenameTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RenameView(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ResetWebViewZoom():Promise<connection.QueryResult>;

export function ResolveDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function ResolveDriverPackageDownloadURL(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ResolveDriverRepositoryURL(arg1:string):Promise<connection.QueryResult>;

export function RestartSecurityUpdate(arg1:app.RestartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function ResultDiffClose(arg1:string):Promise<connection.QueryResult>;

export function ResultDiffCompute(arg1:string):Promise<connection.QueryResult>;

export function ResultDiffPage(arg1:resultdiff.PageRequest):Promise<connection.QueryResult>;

export function ResultDiffStart(arg1:app.ResultDiffStartRequest):Promise<connection.QueryResult>;

export function ResultDiffUploadChunk(arg1:resultdiff.UploadChunkRequest):Promise<connection.QueryResult>;

export function RetrySecurityUpdateCurrentRound(arg1:app.RetrySecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function SaveConnection(arg1:connection.SavedConnectionInput):Promise<connection.SavedConnectionView>;

export function SaveGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function SaveQuery(arg1:connection.SavedQuery):Promise<connection.SavedQuery>;

export function SaveSavedQueryGroup(arg1:connection.SavedQueryGroup):Promise<connection.SavedQueryGroup>;

export function SelectCertificateFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDataRootDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDatabaseFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageFile(arg1:string):Promise<connection.QueryResult>;

export function SelectLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectSQLFileForExecution():Promise<connection.QueryResult>;

export function SelectSSHKeyFile(arg1:string):Promise<connection.QueryResult>;

export function SetApplicationBrandIcon(arg1:string):Promise<connection.QueryResult>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMacNativeWindowControls(arg1:boolean):Promise<void>;

export function SetUpdateChannel(arg1:string):Promise<connection.QueryResult>;

export function SetWindowTranslucency(arg1:number,arg2:number):Promise<void>;

export function Shutdown():Promise<void>;

export function StartSecurityUpdate(arg1:app.StartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function TestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TestGlobalProxyConnection(arg1:connection.TestGlobalProxyInput):Promise<connection.QueryResult>;

export function TestJVMConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TruncateTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function UpdateSQLAuditSettings(arg1:sqlaudit.Settings):Promise<connection.QueryResult>;

export function VerifySQLAuditIntegrity():Promise<connection.QueryResult>;

export function WriteSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;
