// @ts-nocheck
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {sync} from '../models';
import {app} from '../models';
import {jvm} from '../models';
import {redis} from '../models';

export function ApplyChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function ApplyDataRootDirectory(arg1:string,arg2:boolean):Promise<connection.QueryResult>;

export function CancelQuery(arg1:string):Promise<connection.QueryResult>;

export function CancelSQLFileExecution(arg1:string):Promise<connection.QueryResult>;

export function CheckDriverNetworkStatus():Promise<connection.QueryResult>;

export function CheckForUpdates():Promise<connection.QueryResult>;

export function CheckForUpdatesSilently():Promise<connection.QueryResult>;

export function ClearTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function ConfigureDriverRuntimeDirectory(arg1:string):Promise<connection.QueryResult>;

export function ConfigureGlobalProxy(arg1:boolean,arg2:connection.ProxyConfig):Promise<connection.QueryResult>;

export function CreateDatabase(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function CreateSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBCommitTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetAllColumns(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetColumns(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetForeignKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetIndexes(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetTriggers(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryIsolated(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryMulti(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryMultiTransactional(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryWithCancel(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBRollbackTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DataSync(arg1:sync.SyncConfig):Promise<sync.SyncResult>;

export function DataSyncAnalyze(arg1:sync.SyncConfig):Promise<connection.QueryResult>;

export function DataSyncPreview(arg1:sync.SyncConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function DeleteSQLFile(arg1:string):Promise<connection.QueryResult>;

export function DismissSecurityUpdateReminder():Promise<app.SecurityUpdateStatus>;

export function DownloadDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DownloadUpdate():Promise<connection.QueryResult>;

export function DropDatabase(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DropFunction(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DropTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DropView(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DuplicateConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function ExecuteSQLFile(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportConnectionsPackage(arg1:app.ConnectionExportOptions):Promise<connection.QueryResult>;

export function ExportData(arg1:Array<Record<string, any>>,arg2:Array<string>,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportDatabaseSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean):Promise<connection.QueryResult>;

export function ExportQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<connection.QueryResult>;

export function ExportSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ExportTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportTablesDataSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function ExportTablesSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>,arg4:boolean):Promise<connection.QueryResult>;

export function GenerateQueryID():Promise<string>;

export function GetAppInfo():Promise<connection.QueryResult>;

export function GetDataRootDirectoryInfo():Promise<connection.QueryResult>;

export function GetDriverStatusList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionPackageSize(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetEditableSavedConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function GetGlobalProxyConfig():Promise<connection.QueryResult>;

export function GetSavedConnections():Promise<Array<connection.SavedConnectionView>>;

export function GetSecurityUpdateStatus():Promise<app.SecurityUpdateStatus>;

export function ImportConfigFile():Promise<connection.QueryResult>;

export function ImportConnectionsPayload(arg1:string,arg2:string):Promise<Array<connection.SavedConnectionView>>;

export function ImportData(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function ImportDataWithProgress(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ImportLegacyConnections(arg1:Array<connection.SavedConnectionInput>):Promise<Array<connection.SavedConnectionView>>;

export function ImportLegacyGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function InstallLocalDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function InstallUpdateAndRestart():Promise<connection.QueryResult>;

export function JVMApplyChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMCancelDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function JVMExecuteDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:jvm.DiagnosticCommandRequest):Promise<connection.QueryResult>;

export function JVMGetMonitoringHistory(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMListAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListDiagnosticAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListResources(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMPreviewChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMProbeCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMProbeDiagnosticCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStartDiagnosticSession(arg1:connection.ConnectionConfig,arg2:jvm.DiagnosticSessionRequest):Promise<connection.QueryResult>;

export function JVMStartMonitoring(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStopMonitoring(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ListInstalledFontFamilies():Promise<connection.QueryResult>;

export function ListSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function LogWindowDiagnostic(arg1:string,arg2:string):Promise<void>;

export function MongoDiscoverMembers(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function MySQLQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function MySQLShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function OpenDataRootDirectory():Promise<connection.QueryResult>;

export function OpenDownloadedUpdateDirectory():Promise<connection.QueryResult>;

export function OpenDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function OpenSQLFile():Promise<connection.QueryResult>;

export function PreviewChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function PreviewImportFile(arg1:string):Promise<connection.QueryResult>;

export function ReadAppLogTail(arg1:number,arg2:string):Promise<connection.QueryResult>;

export function ReadSQLFile(arg1:string):Promise<connection.QueryResult>;

export function RedisConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisDeleteHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:any):Promise<connection.QueryResult>;

export function RedisDeleteKeys(arg1:connection.ConnectionConfig,arg2:Array<string>):Promise<connection.QueryResult>;

export function RedisExecuteCommand(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisFlushDB(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetServerInfo(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisKeyExists(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisListPush(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisListSet(arg1:connection.ConnectionConfig,arg2:string,arg3:number,arg4:string):Promise<connection.QueryResult>;

export function RedisRenameKey(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RedisScanKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:any,arg4:number):Promise<connection.QueryResult>;

export function RedisSelectDB(arg1:connection.ConnectionConfig,arg2:number):Promise<connection.QueryResult>;

export function RedisSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RedisSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetString(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function RedisSetTTL(arg1:connection.ConnectionConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function RedisStreamAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Record<string, string>,arg4:string):Promise<connection.QueryResult>;

export function RedisStreamDelete(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisTestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisZSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<redis.ZSetMember>):Promise<connection.QueryResult>;

export function RedisZSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RemoveDriverPackage(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameDatabase(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RenameSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RenameView(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ResetWebViewZoom():Promise<connection.QueryResult>;

export function ResolveDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function ResolveDriverPackageDownloadURL(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ResolveDriverRepositoryURL(arg1:string):Promise<connection.QueryResult>;

export function RestartSecurityUpdate(arg1:app.RestartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function RetrySecurityUpdateCurrentRound(arg1:app.RetrySecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function SaveConnection(arg1:connection.SavedConnectionInput):Promise<connection.SavedConnectionView>;

export function SaveGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function SelectCertificateFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDataRootDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDatabaseFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageFile(arg1:string):Promise<connection.QueryResult>;

export function SelectSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectSSHKeyFile(arg1:string):Promise<connection.QueryResult>;

export function SetMacNativeWindowControls(arg1:boolean):Promise<void>;

export function SetWindowTranslucency(arg1:number,arg2:number):Promise<void>;

export function Shutdown():Promise<void>;

export function StartSecurityUpdate(arg1:app.StartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function TestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TestJVMConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TruncateTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function WriteSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;
