// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIChatCancel(arg1) {
  return window['go']['aiservice']['Service']['AIChatCancel'](arg1);
}

export function AIChatSend(arg1, arg2) {
  return window['go']['aiservice']['Service']['AIChatSend'](arg1, arg2);
}

export function AIChatStream(arg1, arg2, arg3) {
  return window['go']['aiservice']['Service']['AIChatStream'](arg1, arg2, arg3);
}

export function AICheckSQL(arg1) {
  return window['go']['aiservice']['Service']['AICheckSQL'](arg1);
}

export function AIDeleteProvider(arg1) {
  return window['go']['aiservice']['Service']['AIDeleteProvider'](arg1);
}

export function AIDeleteSession(arg1) {
  return window['go']['aiservice']['Service']['AIDeleteSession'](arg1);
}

export function AIGetActiveProvider() {
  return window['go']['aiservice']['Service']['AIGetActiveProvider']();
}

export function AIGetBuiltinPrompts() {
  return window['go']['aiservice']['Service']['AIGetBuiltinPrompts']();
}

export function AIGetContextLevel() {
  return window['go']['aiservice']['Service']['AIGetContextLevel']();
}

export function AIGetEditableProvider(arg1) {
  return window['go']['aiservice']['Service']['AIGetEditableProvider'](arg1);
}

export function AIGetProviders() {
  return window['go']['aiservice']['Service']['AIGetProviders']();
}

export function AIGetSafetyLevel() {
  return window['go']['aiservice']['Service']['AIGetSafetyLevel']();
}

export function AIGetSessions() {
  return window['go']['aiservice']['Service']['AIGetSessions']();
}

export function AIListModels() {
  return window['go']['aiservice']['Service']['AIListModels']();
}

export function AILoadSession(arg1) {
  return window['go']['aiservice']['Service']['AILoadSession'](arg1);
}

export function AISaveProvider(arg1) {
  return window['go']['aiservice']['Service']['AISaveProvider'](arg1);
}

export function AISaveSession(arg1, arg2, arg3, arg4) {
  return window['go']['aiservice']['Service']['AISaveSession'](arg1, arg2, arg3, arg4);
}

export function AISetActiveProvider(arg1) {
  return window['go']['aiservice']['Service']['AISetActiveProvider'](arg1);
}

export function AISetContextLevel(arg1) {
  return window['go']['aiservice']['Service']['AISetContextLevel'](arg1);
}

export function AISetSafetyLevel(arg1) {
  return window['go']['aiservice']['Service']['AISetSafetyLevel'](arg1);
}

export function AITestProvider(arg1) {
  return window['go']['aiservice']['Service']['AITestProvider'](arg1);
}
