// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function AICallMCPTool(arg1:string,arg2:string):Promise<ai.MCPToolCallResult>;

export function AIChatCancel(arg1:string):Promise<void>;

export function AIChatSend(arg1:Array<ai.Message>,arg2:Array<ai.Tool>):Promise<Record<string, any>>;

export function AIChatStream(arg1:string,arg2:Array<ai.Message>,arg3:Array<ai.Tool>):Promise<void>;

export function AICheckSQL(arg1:string):Promise<ai.SafetyResult>;

export function AIDeleteMCPServer(arg1:string):Promise<void>;

export function AIDeleteProvider(arg1:string):Promise<void>;

export function AIDeleteSession(arg1:string):Promise<void>;

export function AIDeleteSkill(arg1:string):Promise<void>;

export function AIGetActiveProvider():Promise<string>;

export function AIGetBuiltinPrompts():Promise<Record<string, string>>;

export function AIGetContextLevel():Promise<string>;

export function AIGetEditableProvider(arg1:string):Promise<ai.ProviderConfig>;

export function AIGetMCPClientInstallStatuses():Promise<Array<ai.MCPClientInstallStatus>>;

export function AIGetMCPHTTPServerStatus():Promise<ai.MCPHTTPServerStatus>;

export function AIGetMCPServers():Promise<Array<ai.MCPServerConfig>>;

export function AIGetProviders():Promise<Array<ai.ProviderConfig>>;

export function AIGetSafetyLevel():Promise<string>;

export function AIGetSessions():Promise<Array<Record<string, any>>>;

export function AIGetSkills():Promise<Array<ai.SkillConfig>>;

export function AIGetUserPromptSettings():Promise<ai.UserPromptSettings>;

export function AIInstallClaudeCodeMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallCodexMCP():Promise<ai.MCPClientInstallResult>;

export function AIListMCPTools():Promise<Array<ai.MCPToolDescriptor>>;

export function AIListModels():Promise<Record<string, any>>;

export function AILoadSession(arg1:string):Promise<Record<string, any>>;

export function AISaveMCPServer(arg1:ai.MCPServerConfig):Promise<void>;

export function AISaveProvider(arg1:ai.ProviderConfig):Promise<void>;

export function AISaveSession(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function AISaveSkill(arg1:ai.SkillConfig):Promise<void>;

export function AISaveUserPromptSettings(arg1:ai.UserPromptSettings):Promise<void>;

export function AISetActiveProvider(arg1:string):Promise<void>;

export function AISetContextLevel(arg1:string):Promise<void>;

export function AISetLanguage(arg1:string):Promise<void>;

export function AISetSafetyLevel(arg1:string):Promise<void>;

export function AIStartMCPHTTPServer(arg1:ai.MCPHTTPServerOptions):Promise<ai.MCPHTTPServerStatus>;

export function AIStopMCPHTTPServer():Promise<ai.MCPHTTPServerStatus>;

export function AITestMCPServer(arg1:ai.MCPServerConfig):Promise<Record<string, any>>;

export function AITestProvider(arg1:ai.ProviderConfig):Promise<Record<string, any>>;

export function Shutdown():Promise<void>;
