// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-cc133d2524ceb634",
		"oceanbase":     "src-ac17327184366ff0",
		"diros":         "src-7d4fe439271d0c56",
		"starrocks":     "src-ce9ee22641a32f46",
		"sphinx":        "src-08f5ae54efb3d9df",
		"sqlserver":     "src-bd1323910fc119ac",
		"sqlite":        "src-96dfa25b3042b2d5",
		"duckdb":        "src-8804eb2cdbc89433",
		"dameng":        "src-016e77082aea6718",
		"kingbase":      "src-17728b2ebda94dc9",
		"highgo":        "src-da2e8a9d2e661d3b",
		"vastbase":      "src-da186ac367206c16",
		"opengauss":     "src-54dc852e4c502947",
		"gaussdb":       "src-3bbbffc6991dc8ae",
		"iris":          "src-e798713e492e9a09",
		"mongodb":       "src-2610395b35c2e708",
		"tdengine":      "src-779b9b537f08856f",
		"iotdb":         "src-7edea4aba8d4869e",
		"clickhouse":    "src-d4150c3fb3d1313a",
		"elasticsearch": "src-8086b38d85310b20",
		"trino":         "src-ba947f211ce7b19f",
	}
}
