// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":    "src-4e1ec648c70c87ea",
		"oceanbase":  "src-8e445fc4899d850f",
		"diros":      "src-74927b3809258666",
		"starrocks":  "src-3b5aad8a32f79b61",
		"sphinx":     "src-269bd60a34df47d3",
		"sqlserver":  "src-84553484c72e7253",
		"sqlite":     "src-762863d48f653b89",
		"duckdb":     "src-3e551d777ae96d8d",
		"dameng":     "src-596bebeaa016fc74",
		"kingbase":   "src-2e5a1337b0405c57",
		"highgo":     "src-5a29a1d3685eb6b4",
		"vastbase":   "src-e3cfef65512feb23",
		"opengauss":  "src-58227ba3bc1ec894",
		"mongodb":    "src-57fdd8bfebdcd46e",
		"tdengine":   "src-939715f94df1ec9c",
		"clickhouse": "src-482d62ed565b3e69",
	}
}
