// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-237be74eb89cf64e",
		"oceanbase":     "src-e103b5465c59286a",
		"diros":         "src-cac1fecdcb4f3020",
		"starrocks":     "src-a649837c20f6b0fd",
		"sphinx":        "src-885a99f6ad078ecb",
		"sqlserver":     "src-fabd1f87aba17942",
		"sqlite":        "src-c75f72581f6d7ae1",
		"duckdb":        "src-35a3b88138f7073f",
		"dameng":        "src-7c3f37cbda7974f6",
		"kingbase":      "src-c161f698a520730e",
		"highgo":        "src-01b527826acd35aa",
		"vastbase":      "src-af5bdbd20f3ce3d2",
		"opengauss":     "src-eb07258bd418ae5c",
		"gaussdb":       "src-bd73a0616d917197",
		"iris":          "src-62d1bef85c82f476",
		"mongodb":       "src-95f55020c6481079",
		"tdengine":      "src-817b3f655526b25d",
		"iotdb":         "src-e2a3161c7c81d21c",
		"clickhouse":    "src-2a5d2a885efb8e99",
		"elasticsearch": "src-0f9ee301ddf73d4f",
		"trino":         "src-35f2d68ea9b9db64",
	}
}
